### ISSUE TITLE
mac配置swagger报错

### ISSUE THREAD

**Issue by csjiabin** [super2god/egg-shell-decorators#4]
```
2018-09-26 19:59:39,209 ERROR 48387 nodejs.AppWorkerDiedError: [master] app_worker#1:48398 died (code: 1, signal: null, suicide: false, state: dead), current workers: []
    at Master.onAppExit (/Users/csjiabin/project/nodeJs/part-time/node_modules/egg-cluster/lib/master.js:400:21)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (/Users/csjiabin/project/nodeJs/part-time/node_modules/egg-cluster/lib/utils/messenger.js:133:17)
    at Messenger.send (/Users/csjiabin/project/nodeJs/part-time/node_modules/egg-cluster/lib/utils/messenger.js:98:12)
    at EventEmitter.cluster.on (/Users/csjiabin/project/nodeJs/part-time/node_modules/egg-cluster/lib/master.js:268:22)
    at emitThree (events.js:141:20)
    at EventEmitter.emit (events.js:217:7)
    at ChildProcess.worker.process.once (internal/cluster/master.js:189:13)
    at Object.onceWrapper (events.js:317:30)
name: "AppWorkerDiedError"
pid: 48387
hostname: huangjiabindeMacBook-Pro.local

2018-09-26 19:59:39,210 ERROR 48387 [master] app_worker#1:48398 start fail, exiting with code:1
2018-09-26 19:59:39,210 ERROR 48387 [master] exit with code:1
2018-09-26 19:59:39,226 ERROR 48392 [agent_worker] receive disconnect event on child_process fork mode, exiting with code:110
⚠️  Error: /Users/csjiabin/project/nodeJs/part-time/node_modules/egg-bin/lib/start-cluster {"typescript":true,"baseDir":"/Users/csjiabin/project/nodeJs/part-time","framework":"/Users/csjiabin/project/nodeJs/part-time/node_modules/egg","workers":1} exit with code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
2018-09-26 19:59:39,231 ERROR 48392 [agent_worker] exit with code:110
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! part-time@1.0.0 dev: `egg-bin dev -r egg-ts-helper/register`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the part-time@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/csjiabin/.npm/_logs/2018-09-26T11_59_39_244Z-debug.log
```

**Comment by csjiabin** [comment]
配置是抄你的示例
